### ISSUE TITLE
Move Geta.EPi.Extensions.EnumerableExtensions to other package

### ISSUE THREAD

**Issue by valdisiljuconoks** [Geta/EPi.Extensions#16]
Consider moving these kind of low level .Net enrichment to other package. I don't want to pull EPiServer dependency (because of this package) down to my let's say .Core package.

**Comment by frederikvig** [comment]
I tend to agree to keep this in a separate specific package, but for ease of use and how often we use it in our code we'll for now keep it in the same package.

**Comment by kaspars-ozols** [comment]
Shouldn't improving overall package quality have higher priority than
compatibility in long run? Why can't we do it like EPiServer does when it
comes to breaking changes - add new package/methods and mark old methods as
obsolete so everybody has time to move away from using them?

Take alook around, there are so many copy-pasted .NET class extensions
across all the projects (to name some - string.GenerateSlug(),
IEnumerable.ForEach(), string.JoinStrings(), IEnumerable.EmptyOrNull(),
etc) that could be packed up shared instead.

Usually such extensions live in the Core project which does not and should
not have reference to EPiServer.
