### ISSUE TITLE
Content reference extensions should not be PageData specific

### ISSUE THREAD

**Issue by kaspars-ozols** [Geta/EPi.Extensions#18]
GetChildren expects returned collection to be of type PageData and not IContent. This renders this method useless when used with commerce.

**Comment by frederikvig** [comment]
Use the GetChildre overload where you pass in the type instead. This should be kept as it's to not break existing solutions.

**Comment by kaspars-ozols** [comment]
While of course I can use overload, but I think that current implementation is just misleading. If compatibility is a concern, this method should be marked as obsolete and eventually removed from code base and/or replaced with another (for example, GetChildrenPages).

Helper libraries should be designed as being simple and easy to use. If we keep such things in core library just because we are scared to break anything, then we will end up with unusable library as every time I will have to go through code to see if function is "legacy" or not.
