### ISSUE TITLE
IVersionable - CheckPublishedStatus?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [Geta/EPi.Extensions#19]
Maybe I'm missing something obvious here, but I'd like an extension method like this (from [Vigs blog](http://www.frederikvig.com/2009/05/episerver-extension-methods/), from the EPiServer DLL) for IVersionable:

    public static bool IsPublished(this PageData page)
    {
        return page.StopPublish > DateTime.Now && page.StartPublish < DateTime.Now;
    }

**Comment by frederikvig** [comment]
Sorry for late answer, but you can just do this: page.CheckPublishedStatus(PagePublishedStatus.Published) to see if it's published.
