### ISSUE TITLE
Closest<Type>()

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [Geta/EPi.Extensions#22]
How about something like this? Akin to jQuery's `$().closest('a')`

        public static T Closest<T>(this IContent instance) where T : IContent
        {
            var parentLink = instance.ParentLink;

            while (parentLink != null)
            {
                var parent = parentLink.Get<IContent>();

                if (parent is T)
                {
                    return (T)parent;
                }

                parentLink = parent.ParentLink;
            }

            return default(T);
        }

**Comment by marisks** [comment]
jQuery's meaning of _closest_ is different:
```
For each element in the set, get the first element that matches the selector by testing the element itself and traversing up through its ancestors in the DOM tree.
```
But EPiServer has similar functionality on _IContentLoader_ - _GetAncestors_ method. I think that this extension should be called _FirstAncestor_ and use _GetAncestors_ method to get a first parent of type.

**Comment by bjorn-ali-goransson** [comment]
But FirstAncestor() is so similar to Ancestors().First() that it's misleading.

Let's not get hanged up on the jQuery reference. Would this perhaps be achieved with GetAncestors().OfType<T>().First() ?

**Comment by marisks** [comment]
Yes, it can be achieved with:
```
loader.GetAncestors(instance.ContentLink).OfType<T>().FirstOrDefault();
```

**Comment by marisks** [comment]
An extension might look like this:
```
public static T FirstAncestor<T>(this IContent instance)
	where T : IContent
{
	var loader = ServiceLocator.Current.GetInstance<IContentLoader>();
	return loader.GetAncestors(instance.ContentLink).OfType<T>().FirstOrDefault();
}
```

I do not think that _FirstAncestor<T>_ is a misleading name - it explicitly says that it returns a first ancestor of provided type.

**Comment by kaspars-ozols** [comment]
I also think that `FirstAncestor<T>` is a bit misleading as search direction is not known if you don't know context of this issue.

IMHO best naming would be combination of both previously mentioned -  `ClosestAncestor<T>`. Name explicitly says that it will search only ancestors and return one that is the closest to the child item.

**Comment by bjorn-ali-goransson** [comment]
Right, now you reminded me of why I didn't use the Ancestors().First() in
the first place. Thanks

2016-10-24 18:47 GMT+02:00 Kaspars Ozols <notifications@github.com>:

**Comment by bjorn-ali-goransson** [comment]
Fair enough, LGTM

2016-10-24 15:11 GMT+02:00 Māris Krivtežs <notifications@github.com>:
