### ISSUE TITLE
`GetFriendlyUrl` strips off external host name when page has shortcut set to external resource

### ISSUE THREAD

**Issue by kaspars-ozols** [Geta/EPi.Extensions#40]
How to reproduce:
* Create a new CMS page in site (https://www.my-cms.com) that has shortcut set to external URL (for example, https://www.my-external-site.com/unicorns)
* Retrieve content reference to created page and call `GetFriendlyUrl` with no parameters on it

Result:
`GetFriendlyUrl` returns "/unicorns". If that is rendered anywhere on page, this effectively is translated into "https://www.my-cms.com/unicorns"

Expected result:
`GetFriendlyUrl` should return url with correct domain name - "https://www.my-external-site.com/unicorns".
`GetFriendlyUrl` should remove host name only if it is not external. I could call `GetFriendlyUrl` and pass in parameter `includeHost` as true, but then it renders default overload useless as editor can add shortcut at any time.

**Comment by gatisb** [comment]
Just got new bug about this, can this be fixed?

**Comment by gatisb** [comment]
tested version: Geta.EPi.Extensions.2.0.2

**Comment by gatisb** [comment]
with: EPiServer.CMS.Core.11.9.1

**Comment by gatisb** [comment]
confirmed in 2.0.3 as well

**Comment by gatisb** [comment]
fixed in 2.0.4

**Comment by gatisb** [comment]
@kaspars-ozols we have fixed this, thank you for patience
