### ISSUE TITLE
GetAncestors ?

### ISSUE THREAD

**Issue by bornemix** [Geta/EPi.Extensions#6]

**Comment by bornemix** [comment]
I realise I'm being ridiculous here..: Should GetAncestors be removed?

It's implemented in the latest EPiServer.Core.PageDataExtensions, so now everyone who is both using Geta EPi Extensions and EPiServer are getting ambigous reference errors.

Also, what if EPiServer implements some other method already implemented in Geta EPi Extensions?

**Comment by bornemix** [comment]
Wait - my bad, this extension method was defined on EPiServer.Core, but in our own assembly waiting for the nuget package to be updated.

But the general question still remains, I guess.

**Comment by frederikvig** [comment]
In cases like these we would remove our version. We want developers to use EPiServer's API, these methods are enhancements and useful utilities, not replacements for what is built in.
